name: Learn Action

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: create txt
        run: |
          echo "Hello world" > note.txt
          pwd
          ls -al
          cat note.txt
      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: ./note.txt
      - name: test
        run: |
          pwd
          ls -al


